/*
 * Copyright 2010 Christian Schindelhauer, Peter Thiemann, Faisal Aslam, Luminous Fennell and Gidon Ernst.
 * All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 * 
 * This code is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * only, as published by the Free Software Foundation.
 * 
 * This code is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License version 3 for more details (a copy is
 * included in the LICENSE file that accompanied this code).
 * 
 * You should have received a copy of the GNU General Public License
 * version 3 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 * 
 * Please contact Faisal Aslam 
 * (aslam AT informatik.uni-freibug.de or studentresearcher AT gmail.com)
 * if you need additional information or have any questions.
 */
package takatuka.vm.autoGenerated;

import java.io.*;
import takatuka.classreader.logic.file.*;
import takatuka.classreader.logic.util.*;
/**
 * 
 * Description:
 * <p>
 *
 * </p> 
 * @author Faisal Aslam
 * @version 1.0
 */
public class HeaderFileConstants {

    public static final String AUTO_GENERATED_MSG = "/* ***** This is an" +
            " autogenerated file. (time=" +
            System.currentTimeMillis() + ") **** */ \n\n";

    public static String headerStart(String headerFileName) {
        if (headerFileName == null) {
            Miscellaneous.printlnErr("Header file name is null. Check you configuration file ");
            Miscellaneous.exit();
        }
        if (!headerFileName.endsWith(".h")) {
            Miscellaneous.printlnErr("Header file name must end with .h i.e " + headerFileName);
            Miscellaneous.exit();
        }
        headerFileName = headerFileName.replace("\\", "/");
        if (headerFileName.indexOf("/") != -1) {
            headerFileName = headerFileName.substring(headerFileName.lastIndexOf("/") + 1);
        }
        headerFileName = (headerFileName.replace(".", "_")).toUpperCase();
        String upercaseHeaderName = "#ifndef" + " " + headerFileName;
        upercaseHeaderName += "\n#define" + " " + headerFileName;
        return AUTO_GENERATED_MSG + upercaseHeaderName + "\n\n";
    }

    public static String headerEnd() {
        return "\n\n#endif\n";
    }

    public static void writeHeaderFile(String headerFileData, String headerFileName) {
        try {
            String contents = headerStart(headerFileName) + "\n\n";
            contents += headerFileData + "\n" + HeaderFileConstants.headerEnd();
            File file = new File(headerFileName);
            ClassFileWriter.writeFile(new File(file.getAbsolutePath()),
                    contents);
        } catch (Exception d) {
            d.printStackTrace();
            Miscellaneous.exit();
        }
    }

    private HeaderFileConstants() {
    }
}
